### ISSUE TITLE
local variable 'elb_hours' referenced before assignment: UnboundLocalError

### ISSUE THREAD

**Issue by AlexOugh** [ConcurrenyLabs/aws-pricing-tools#1]
It looks like it is failed when there are no lbs with the given tags.

local variable 'elb_hours' referenced before assignment: UnboundLocalError
Traceback (most recent call last):
File "/var/task/functions/calculate-near-realtime.py", line 102, in handler
elb_cost = ec2pricing.calculate(region=region, elbHours=elb_hours, elbDataProcessedGb=elb_data_processed_gb)
UnboundLocalError: local variable 'elb_hours' referenced before assignment

**Comment by concurrencylabs** [comment]
Thanks for pointing that out, I will look into it now.

**Comment by concurrencylabs** [comment]
The basic issue where no ELB would trigger the error is fixed -  I am testing for other scenarios that could cause failure. Fix is pushed and .zip file that CloudFormation template uses to create the function is updated.

**Comment by concurrencylabs** [comment]
The issue is fixed. If you created the function using CloudFormation, you can update the stack by pointing to the location of the latest CloudFormation template: http://concurrencylabs-cfn-templates.s3.amazonaws.com/lambda-near-realtime-pricing/function-plus-schedule.json

Or you can delete the stack and create a new one, using the template URL above.
