### ISSUE TITLE
Question: Cross account functionality and tag optional

### ISSUE THREAD

**Issue by dorian-coygo** [ConcurrenyLabs/aws-pricing-tools#9]
Hi,

First off, I wanted to thank you for an awesome tool :). AWS is extremely slow with releasing a GA version of providing near real time pricing. This has been extremely helpful in forecasting potential budget issue.

I wanted to throw out a use case here and get your opinion before forking and building a similar solution.

**A client has the following use case:**
* They create multiple accounts for users and give full control of those accounts to the user. 
* The user may start/stop/control all of the resources in the account. 
* The user has a specific budget they must adhere to that. 
* The budget is managed externally. 
* The client has a root access to all the accounts and can monitor/start/stop resources as needed.

**The client wants to know to be able to do the following:**
* Monitor the cost of multiple accounts.
* Not have to run resources in the user account (as they could stop them after giving access)
* Not worry about tag enforcement
* Able to shutdown resources if account is nearing the budget issue.

**My thoughts:**
I was thinking of utilizing this solution combined with [Cloud Custodian](https://github.com/cloud-custodian/cloud-custodian) in order to monitor and enforce resource utilization within a given budget.

**One way of doing this could be:**
1. Modify the code in this repo and add the ability to use this cross-accounts by running this resource in a "root" account. My guess this would require most of the effort.
2. Modify the code in this repo and add the ability to specify a tag as optional and just gather all resources (there is probably a similar use case of 'include everything but X tag'). My guess is this effort would be minimal
3. Use cloud custodian to look at the output of these metrics and then create rules to act on it

Before I run off, I wanted to get your thoughts to see if you think this would be something useful to add to this project or if I should spin it off and use this as a base. If you think this would be useful, do you have any technical considerations we should think through in order to get a PR accepted.

**Comment by concurrencylabs** [comment]
First off, thanks for your feedback. The use case you're describing is interesting. One option for the Lambda function to access multiple AWS accounts is for it to assume IAM Roles that grant access to such accounts. You'd need to add logic in the Lambda function to initialize SDK clients with access to those accounts, by assuming an IAM Role. The steps might look like this:

- Create an IAM user in the main (root) AWS account.
- Create IAM roles in other accounts, granting permissions to the root AWS account.
- Let the Lambda function know the IAM role and account you want to access, so it can initialize clients assuming such IAM role and the IAM user in the root account. Maybe this can be done in the CloudWatch scheduled event. The logic could be that if no IAM role is specified in the event use the default Lambda role, otherwise use the provided IAM role. Another option would be to provide the IAM Role(s) in an environment variable.
- If you want to make tags optional, this could be done too, just keep in mind that Lambda execution might take much longer, so make sure the timeout is appropriate for the additional execution time.

I hope this helps.

**Comment by dorian-coygo** [comment]
I (or someone I work with) will probably fork this repo and I will put a link to it here after it is complete. Feel free to close the issue or keep it open. 

The creation of the IAM user on the (root) AWS account could be possible in the stack and we could possible create those IAM roles in the stack as well. I would have to look at limitations of lambda stacks creating IAM roles in a different account though.

I think we would then store an array/object of account numbers + IAM roles somewhere (probably in the lambda for now). We could probably include a section in the creating of the stack for people to specify it.

Will remember to keep the timeout of the lambda in mind because we may have to create multiple lambdas based on how many accounts are selected. This will be more of an optimization in the future.

Thanks again!
